version: "3.8"
services:
  openprize:
    image: mhjp/openprize:latest
    hostname: openprize
    restart: unless-stopped
    networks:
      traefik_net: null
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - openprize:/app/db
    labels:
      - traefik.enable=true
      - traefik.http.routers.openprize.rule=Host(`openprize.${FQDN}`)
      - traefik.http.routers.openprize.entrypoints=websecure
      - traefik.http.routers.openprize.middlewares=openprize-compress,openprize-errorpages
      - traefik.http.services.openprize.loadbalancer.server.port=5000
      - traefik.http.middlewares.openprize-compress.compress=true
      - traefik.http.middlewares.openprize-errorpages.errors.status=400-599
      - traefik.http.middlewares.openprize-errorpages.errors.service=error
      - traefik.http.middlewares.openprize-errorpages.errors.query=/{status}.html
    command: flask run --host=0.0.0.0
##############
## Networks ##
##############
networks:
  traefik_net:
    external: true
#############
## Volumes ##
#############
volumes:
  openprize: null
