version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./src:/app
      - ./node_modules/tw-elements/js/:/app/static/js/
    environment:
      FLASK_ENV: ${FLASK_ENV}
    command: flask run --host=0.0.0.0
