services:
  openprize:
    image: ghcr.io/mhjp-coder/openprize:latest
    hostname: openprize
    restart: unless-stopped
    networks:
      traefik_net:
    volumes:
      - data:/app/db
    labels:
      - traefik.enable=true
      - traefik.http.routers.openprize.rule=Host(`openprize.${FQDN}`)
      - traefik.http.routers.openprize.entrypoints=websecure
      - traefik.http.routers.openprize.middlewares=openprize-auth
      - traefik.http.middlewares.openprize-auth.basicauth.users=${OP_ADMIN_PASS}
      - traefik.http.services.openprize.loadbalancer.server.port=5000
    command: flask run --host=0.0.0.0
##############
## Networks ##
##############
networks:
  traefik_net:
    external: true
#############
## Volumes ##
#############
volumes:
  data:
